### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by omnicortex** [debian-hub/deb#1]
Last commit is 2 years ago.  Is there any other similar project?

**Comment by jakbin** [comment]
I hosted server on heroku . Now heroku is not free . That's why I leave this project.

**Comment by jakbin** [comment]
I hosted server on heroku . Now heroku is not free . That's why I leave this project.

**Comment by omnicortex** [comment]
I see. I hope you will find another free hosting service soon. Thanks for this project.

**Comment by jakbin** [comment]
Hey @omnicortex, will you help me to bring back this project alive again ?

**Comment by omnicortex** [comment]
Hi @jakbin. I have been looking for similar solutions and found this project called [dynapt](https://git.kaki87.net/KaKi87/dynapt).  It has pretty much the same features (it also supports AppImage) and the author is trying to stabilize it for a release. See this [gist](https://gist.github.com/KaKi87/f620788e9901abbfef4978eb7ad358b4). I think we should wait to test out the stable version of `dynapt` to avoid duplicating efforts.
